server:
  port: 8081

spring:
  profiles:
    active: test


wx:
  config:
    originalid: gh_ce466ae81f85
    appid:  wx501a1603b0e3c03d
    token: theRegion
    auth:
      defaultBase64EncodedSecretKey: B*B^D%fe


chat:
  config:
    pers: b8b6

